name: logindemo

packages:
  - packages/**
  - /**

scripts:
  analyze:
    run: melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages.

  format: melos exec -- "flutter format ."

  fix_hints: melos exec -- "dart fix —apply ."

  flutter_test: flutter test

  build_runner: |
    melos exec --depends-on="build_runner" --  $runner
    env:
    runner: flutter pub run build_runner build --delete-conflicting-outputs

  build_relese:
    run: flutter build apk