name: logindemo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:

  bootstrap:
    path: packages/bootstrap
  # check my packages on https://pub.dev/publishers/flutterbots.dev/packages and thanks
  # note: I use rxdart in this  package
  bot_storage: 1.0.2
  core:
    path: packages/core
  cupertino_icons: ^1.0.0
  dio: ^4.0.6
  design:
    path: packages/design
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_riverpod: ^2.0.0-dev.5
  flutter_staggered_animations: ^1.0.0
  fluro: ^2.0.3
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  network:
    path: packages/network
  reactive_forms: ^11.0.1
  rxdart: ^0.27.3
  hive: ^2.1.0
  path_provider: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  freezed: ^2.0.2
  json_serializable: ^6.1.6
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
